#include "hardware.h"
#include "utils.h"
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>



union Register register_AF;
union Register register_BC;
union Register register_DE;
union Register register_HL;
union Register sp;
WORD pc;

BYTE screen[160][144];

struct Instruction {
    char *mnemonic;
    BYTE bytes;
    BYTE cycles;
    bool immediate;
    void *execute;
};

void not_implemented() {
    LOG_E("This instruction is not yet implemented");
    exit(0);
}

struct Instruction unprefixed_instructions[256] = {
    [0x00] = {"NOP", 1, 4, true, not_implemented},
    [0x01] = {"LD BC", 3, 12, true, not_implemented},
    [0x02] = {"LD BC", 1, 8, false, not_implemented},
    [0x03] = {"INC BC", 1, 8, true, not_implemented},
    [0x04] = {"INC B", 1, 4, true, not_implemented},
    [0x05] = {"DEC B", 1, 4, true, not_implemented},
    [0x06] = {"LD B", 2, 8, true, not_implemented},
    [0x07] = {"RLCA", 1, 4, true, not_implemented},
    [0x08] = {"LD a16", 3, 20, false, not_implemented},
    [0x09] = {"ADD HL", 1, 8, true, not_implemented},
    [0x0A] = {"LD A", 1, 8, false, not_implemented},
    [0x0B] = {"DEC BC", 1, 8, true, not_implemented},
    [0x0C] = {"INC C", 1, 4, true, not_implemented},
    [0x0D] = {"DEC C", 1, 4, true, not_implemented},
    [0x0E] = {"LD C", 2, 8, true, not_implemented},
    [0x0F] = {"RRCA", 1, 4, true, not_implemented},
    [0x10] = {"STOP n8", 2, 4, true, not_implemented},
    [0x11] = {"LD DE", 3, 12, true, not_implemented},
    [0x12] = {"LD DE", 1, 8, false, not_implemented},
    [0x13] = {"INC DE", 1, 8, true, not_implemented},
    [0x14] = {"INC D", 1, 4, true, not_implemented},
    [0x15] = {"DEC D", 1, 4, true, not_implemented},
    [0x16] = {"LD D", 2, 8, true, not_implemented},
    [0x17] = {"RLA", 1, 4, true, not_implemented},
    [0x18] = {"JR e8", 2, 12, true, not_implemented},
    [0x19] = {"ADD HL", 1, 8, true, not_implemented},
    [0x1A] = {"LD A", 1, 8, false, not_implemented},
    [0x1B] = {"DEC DE", 1, 8, true, not_implemented},
    [0x1C] = {"INC E", 1, 4, true, not_implemented},
    [0x1D] = {"DEC E", 1, 4, true, not_implemented},
    [0x1E] = {"LD E", 2, 8, true, not_implemented},
    [0x1F] = {"RRA", 1, 4, true, not_implemented},
    [0x20] = {"JR NZ", 2, 12, true, not_implemented},
    [0x21] = {"LD HL", 3, 12, true, not_implemented},
    [0x22] = {"LD HL", 1, 8, false, not_implemented},
    [0x23] = {"INC HL", 1, 8, true, not_implemented},
    [0x24] = {"INC H", 1, 4, true, not_implemented},
    [0x25] = {"DEC H", 1, 4, true, not_implemented},
    [0x26] = {"LD H", 2, 8, true, not_implemented},
    [0x27] = {"DAA", 1, 4, true, not_implemented},
    [0x28] = {"JR Z", 2, 12, true, not_implemented},
    [0x29] = {"ADD HL", 1, 8, true, not_implemented},
    [0x2A] = {"LD A", 1, 8, false, not_implemented},
    [0x2B] = {"DEC HL", 1, 8, true, not_implemented},
    [0x2C] = {"INC L", 1, 4, true, not_implemented},
    [0x2D] = {"DEC L", 1, 4, true, not_implemented},
    [0x2E] = {"LD L", 2, 8, true, not_implemented},
    [0x2F] = {"CPL", 1, 4, true, not_implemented},
    [0x30] = {"JR NC", 2, 12, true, not_implemented},
    [0x31] = {"LD SP", 3, 12, true, not_implemented},
    [0x32] = {"LD HL", 1, 8, false, not_implemented},
    [0x33] = {"INC SP", 1, 8, true, not_implemented},
    [0x34] = {"INC HL", 1, 12, false, not_implemented},
    [0x35] = {"DEC HL", 1, 12, false, not_implemented},
    [0x36] = {"LD HL", 2, 12, false, not_implemented},
    [0x37] = {"SCF", 1, 4, true, not_implemented},
    [0x38] = {"JR C", 2, 12, true, not_implemented},
    [0x39] = {"ADD HL", 1, 8, true, not_implemented},
    [0x3A] = {"LD A", 1, 8, false, not_implemented},
    [0x3B] = {"DEC SP", 1, 8, true, not_implemented},
    [0x3C] = {"INC A", 1, 4, true, not_implemented},
    [0x3D] = {"DEC A", 1, 4, true, not_implemented},
    [0x3E] = {"LD A", 2, 8, true, not_implemented},
    [0x3F] = {"CCF", 1, 4, true, not_implemented},
    [0x40] = {"LD B", 1, 4, true, not_implemented},
    [0x41] = {"LD B", 1, 4, true, not_implemented},
    [0x42] = {"LD B", 1, 4, true, not_implemented},
    [0x43] = {"LD B", 1, 4, true, not_implemented},
    [0x44] = {"LD B", 1, 4, true, not_implemented},
    [0x45] = {"LD B", 1, 4, true, not_implemented},
    [0x46] = {"LD B", 1, 8, false, not_implemented},
    [0x47] = {"LD B", 1, 4, true, not_implemented},
    [0x48] = {"LD C", 1, 4, true, not_implemented},
    [0x49] = {"LD C", 1, 4, true, not_implemented},
    [0x4A] = {"LD C", 1, 4, true, not_implemented},
    [0x4B] = {"LD C", 1, 4, true, not_implemented},
    [0x4C] = {"LD C", 1, 4, true, not_implemented},
    [0x4D] = {"LD C", 1, 4, true, not_implemented},
    [0x4E] = {"LD C", 1, 8, false, not_implemented},
    [0x4F] = {"LD C", 1, 4, true, not_implemented},
    [0x50] = {"LD D", 1, 4, true, not_implemented},
    [0x51] = {"LD D", 1, 4, true, not_implemented},
    [0x52] = {"LD D", 1, 4, true, not_implemented},
    [0x53] = {"LD D", 1, 4, true, not_implemented},
    [0x54] = {"LD D", 1, 4, true, not_implemented},
    [0x55] = {"LD D", 1, 4, true, not_implemented},
    [0x56] = {"LD D", 1, 8, false, not_implemented},
    [0x57] = {"LD D", 1, 4, true, not_implemented},
    [0x58] = {"LD E", 1, 4, true, not_implemented},
    [0x59] = {"LD E", 1, 4, true, not_implemented},
    [0x5A] = {"LD E", 1, 4, true, not_implemented},
    [0x5B] = {"LD E", 1, 4, true, not_implemented},
    [0x5C] = {"LD E", 1, 4, true, not_implemented},
    [0x5D] = {"LD E", 1, 4, true, not_implemented},
    [0x5E] = {"LD E", 1, 8, false, not_implemented},
    [0x5F] = {"LD E", 1, 4, true, not_implemented},
    [0x60] = {"LD H", 1, 4, true, not_implemented},
    [0x61] = {"LD H", 1, 4, true, not_implemented},
    [0x62] = {"LD H", 1, 4, true, not_implemented},
    [0x63] = {"LD H", 1, 4, true, not_implemented},
    [0x64] = {"LD H", 1, 4, true, not_implemented},
    [0x65] = {"LD H", 1, 4, true, not_implemented},
    [0x66] = {"LD H", 1, 8, false, not_implemented},
    [0x67] = {"LD H", 1, 4, true, not_implemented},
    [0x68] = {"LD L", 1, 4, true, not_implemented},
    [0x69] = {"LD L", 1, 4, true, not_implemented},
    [0x6A] = {"LD L", 1, 4, true, not_implemented},
    [0x6B] = {"LD L", 1, 4, true, not_implemented},
    [0x6C] = {"LD L", 1, 4, true, not_implemented},
    [0x6D] = {"LD L", 1, 4, true, not_implemented},
    [0x6E] = {"LD L", 1, 8, false, not_implemented},
    [0x6F] = {"LD L", 1, 4, true, not_implemented},
    [0x70] = {"LD HL", 1, 8, false, not_implemented},
    [0x71] = {"LD HL", 1, 8, false, not_implemented},
    [0x72] = {"LD HL", 1, 8, false, not_implemented},
    [0x73] = {"LD HL", 1, 8, false, not_implemented},
    [0x74] = {"LD HL", 1, 8, false, not_implemented},
    [0x75] = {"LD HL", 1, 8, false, not_implemented},
    [0x76] = {"HALT", 1, 4, true, not_implemented},
    [0x77] = {"LD HL", 1, 8, false, not_implemented},
    [0x78] = {"LD A", 1, 4, true, not_implemented},
    [0x79] = {"LD A", 1, 4, true, not_implemented},
    [0x7A] = {"LD A", 1, 4, true, not_implemented},
    [0x7B] = {"LD A", 1, 4, true, not_implemented},
    [0x7C] = {"LD A", 1, 4, true, not_implemented},
    [0x7D] = {"LD A", 1, 4, true, not_implemented},
    [0x7E] = {"LD A", 1, 8, false, not_implemented},
    [0x7F] = {"LD A", 1, 4, true, not_implemented},
    [0x80] = {"ADD A", 1, 4, true, not_implemented},
    [0x81] = {"ADD A", 1, 4, true, not_implemented},
    [0x82] = {"ADD A", 1, 4, true, not_implemented},
    [0x83] = {"ADD A", 1, 4, true, not_implemented},
    [0x84] = {"ADD A", 1, 4, true, not_implemented},
    [0x85] = {"ADD A", 1, 4, true, not_implemented},
    [0x86] = {"ADD A", 1, 8, false, not_implemented},
    [0x87] = {"ADD A", 1, 4, true, not_implemented},
    [0x88] = {"ADC A", 1, 4, true, not_implemented},
    [0x89] = {"ADC A", 1, 4, true, not_implemented},
    [0x8A] = {"ADC A", 1, 4, true, not_implemented},
    [0x8B] = {"ADC A", 1, 4, true, not_implemented},
    [0x8C] = {"ADC A", 1, 4, true, not_implemented},
    [0x8D] = {"ADC A", 1, 4, true, not_implemented},
    [0x8E] = {"ADC A", 1, 8, false, not_implemented},
    [0x8F] = {"ADC A", 1, 4, true, not_implemented},
    [0x90] = {"SUB A", 1, 4, true, not_implemented},
    [0x91] = {"SUB A", 1, 4, true, not_implemented},
    [0x92] = {"SUB A", 1, 4, true, not_implemented},
    [0x93] = {"SUB A", 1, 4, true, not_implemented},
    [0x94] = {"SUB A", 1, 4, true, not_implemented},
    [0x95] = {"SUB A", 1, 4, true, not_implemented},
    [0x96] = {"SUB A", 1, 8, false, not_implemented},
    [0x97] = {"SUB A", 1, 4, true, not_implemented},
    [0x98] = {"SBC A", 1, 4, true, not_implemented},
    [0x99] = {"SBC A", 1, 4, true, not_implemented},
    [0x9A] = {"SBC A", 1, 4, true, not_implemented},
    [0x9B] = {"SBC A", 1, 4, true, not_implemented},
    [0x9C] = {"SBC A", 1, 4, true, not_implemented},
    [0x9D] = {"SBC A", 1, 4, true, not_implemented},
    [0x9E] = {"SBC A", 1, 8, false, not_implemented},
    [0x9F] = {"SBC A", 1, 4, true, not_implemented},
    [0xA0] = {"AND A", 1, 4, true, not_implemented},
    [0xA1] = {"AND A", 1, 4, true, not_implemented},
    [0xA2] = {"AND A", 1, 4, true, not_implemented},
    [0xA3] = {"AND A", 1, 4, true, not_implemented},
    [0xA4] = {"AND A", 1, 4, true, not_implemented},
    [0xA5] = {"AND A", 1, 4, true, not_implemented},
    [0xA6] = {"AND A", 1, 8, false, not_implemented},
    [0xA7] = {"AND A", 1, 4, true, not_implemented},
    [0xA8] = {"XOR A", 1, 4, true, not_implemented},
    [0xA9] = {"XOR A", 1, 4, true, not_implemented},
    [0xAA] = {"XOR A", 1, 4, true, not_implemented},
    [0xAB] = {"XOR A", 1, 4, true, not_implemented},
    [0xAC] = {"XOR A", 1, 4, true, not_implemented},
    [0xAD] = {"XOR A", 1, 4, true, not_implemented},
    [0xAE] = {"XOR A", 1, 8, false, not_implemented},
    [0xAF] = {"XOR A", 1, 4, true, not_implemented},
    [0xB0] = {"OR A", 1, 4, true, not_implemented},
    [0xB1] = {"OR A", 1, 4, true, not_implemented},
    [0xB2] = {"OR A", 1, 4, true, not_implemented},
    [0xB3] = {"OR A", 1, 4, true, not_implemented},
    [0xB4] = {"OR A", 1, 4, true, not_implemented},
    [0xB5] = {"OR A", 1, 4, true, not_implemented},
    [0xB6] = {"OR A", 1, 8, false, not_implemented},
    [0xB7] = {"OR A", 1, 4, true, not_implemented},
    [0xB8] = {"CP A", 1, 4, true, not_implemented},
    [0xB9] = {"CP A", 1, 4, true, not_implemented},
    [0xBA] = {"CP A", 1, 4, true, not_implemented},
    [0xBB] = {"CP A", 1, 4, true, not_implemented},
    [0xBC] = {"CP A", 1, 4, true, not_implemented},
    [0xBD] = {"CP A", 1, 4, true, not_implemented},
    [0xBE] = {"CP A", 1, 8, false, not_implemented},
    [0xBF] = {"CP A", 1, 4, true, not_implemented},
    [0xC0] = {"RET NZ", 1, 20, true, not_implemented},
    [0xC1] = {"POP BC", 1, 12, true, not_implemented},
    [0xC2] = {"JP NZ", 3, 16, true, not_implemented},
    [0xC3] = {"JP a16", 3, 16, true, not_implemented},
    [0xC4] = {"CALL NZ", 3, 24, true, not_implemented},
    [0xC5] = {"PUSH BC", 1, 16, true, not_implemented},
    [0xC6] = {"ADD A", 2, 8, true, not_implemented},
    [0xC7] = {"RST $00", 1, 16, true, not_implemented},
    [0xC8] = {"RET Z", 1, 20, true, not_implemented},
    [0xC9] = {"RET", 1, 16, true, not_implemented},
    [0xCA] = {"JP Z", 3, 16, true, not_implemented},
    [0xCB] = {"PREFIX", 1, 4, true, not_implemented},
    [0xCC] = {"CALL Z", 3, 24, true, not_implemented},
    [0xCD] = {"CALL a16", 3, 24, true, not_implemented},
    [0xCE] = {"ADC A", 2, 8, true, not_implemented},
    [0xCF] = {"RST $08", 1, 16, true, not_implemented},
    [0xD0] = {"RET NC", 1, 20, true, not_implemented},
    [0xD1] = {"POP DE", 1, 12, true, not_implemented},
    [0xD2] = {"JP NC", 3, 16, true, not_implemented},
    [0xD3] = {"ILLEGAL_D3", 1, 4, true, not_implemented},
    [0xD4] = {"CALL NC", 3, 24, true, not_implemented},
    [0xD5] = {"PUSH DE", 1, 16, true, not_implemented},
    [0xD6] = {"SUB A", 2, 8, true, not_implemented},
    [0xD7] = {"RST $10", 1, 16, true, not_implemented},
    [0xD8] = {"RET C", 1, 20, true, not_implemented},
    [0xD9] = {"RETI", 1, 16, true, not_implemented},
    [0xDA] = {"JP C", 3, 16, true, not_implemented},
    [0xDB] = {"ILLEGAL_DB", 1, 4, true, not_implemented},
    [0xDC] = {"CALL C", 3, 24, true, not_implemented},
    [0xDD] = {"ILLEGAL_DD", 1, 4, true, not_implemented},
    [0xDE] = {"SBC A", 2, 8, true, not_implemented},
    [0xDF] = {"RST $18", 1, 16, true, not_implemented},
    [0xE0] = {"LDH a8", 2, 12, false, not_implemented},
    [0xE1] = {"POP HL", 1, 12, true, not_implemented},
    [0xE2] = {"LDH C", 1, 8, false, not_implemented},
    [0xE3] = {"ILLEGAL_E3", 1, 4, true, not_implemented},
    [0xE4] = {"ILLEGAL_E4", 1, 4, true, not_implemented},
    [0xE5] = {"PUSH HL", 1, 16, true, not_implemented},
    [0xE6] = {"AND A", 2, 8, true, not_implemented},
    [0xE7] = {"RST $20", 1, 16, true, not_implemented},
    [0xE8] = {"ADD SP", 2, 16, true, not_implemented},
    [0xE9] = {"JP HL", 1, 4, true, not_implemented},
    [0xEA] = {"LD a16", 3, 16, false, not_implemented},
    [0xEB] = {"ILLEGAL_EB", 1, 4, true, not_implemented},
    [0xEC] = {"ILLEGAL_EC", 1, 4, true, not_implemented},
    [0xED] = {"ILLEGAL_ED", 1, 4, true, not_implemented},
    [0xEE] = {"XOR A", 2, 8, true, not_implemented},
    [0xEF] = {"RST $28", 1, 16, true, not_implemented},
    [0xF0] = {"LDH A", 2, 12, false, not_implemented},
    [0xF1] = {"POP AF", 1, 12, true, not_implemented},
    [0xF2] = {"LDH A", 1, 8, false, not_implemented},
    [0xF3] = {"DI", 1, 4, true, not_implemented},
    [0xF4] = {"ILLEGAL_F4", 1, 4, true, not_implemented},
    [0xF5] = {"PUSH AF", 1, 16, true, not_implemented},
    [0xF6] = {"OR A", 2, 8, true, not_implemented},
    [0xF7] = {"RST $30", 1, 16, true, not_implemented},
    [0xF8] = {"LD HL", 2, 12, true, not_implemented},
    [0xF9] = {"LD SP", 1, 8, true, not_implemented},
    [0xFA] = {"LD A", 3, 16, false, not_implemented},
    [0xFB] = {"EI", 1, 4, true, not_implemented},
    [0xFC] = {"ILLEGAL_FC", 1, 4, true, not_implemented},
    [0xFD] = {"ILLEGAL_FD", 1, 4, true, not_implemented},
    [0xFE] = {"CP A", 2, 8, true, not_implemented},
    [0xFF] = {"RST $38", 1, 16, true, not_implemented},
};

struct Instruction prefixed_instructions[256] = {
    [0x00] = {"RLC B", 2, 8, true, not_implemented},
    [0x01] = {"RLC C", 2, 8, true, not_implemented},
    [0x02] = {"RLC D", 2, 8, true, not_implemented},
    [0x03] = {"RLC E", 2, 8, true, not_implemented},
    [0x04] = {"RLC H", 2, 8, true, not_implemented},
    [0x05] = {"RLC L", 2, 8, true, not_implemented},
    [0x06] = {"RLC HL", 2, 16, false, not_implemented},
    [0x07] = {"RLC A", 2, 8, true, not_implemented},
    [0x08] = {"RRC B", 2, 8, true, not_implemented},
    [0x09] = {"RRC C", 2, 8, true, not_implemented},
    [0x0A] = {"RRC D", 2, 8, true, not_implemented},
    [0x0B] = {"RRC E", 2, 8, true, not_implemented},
    [0x0C] = {"RRC H", 2, 8, true, not_implemented},
    [0x0D] = {"RRC L", 2, 8, true, not_implemented},
    [0x0E] = {"RRC HL", 2, 16, false, not_implemented},
    [0x0F] = {"RRC A", 2, 8, true, not_implemented},
    [0x10] = {"RL B", 2, 8, true, not_implemented},
    [0x11] = {"RL C", 2, 8, true, not_implemented},
    [0x12] = {"RL D", 2, 8, true, not_implemented},
    [0x13] = {"RL E", 2, 8, true, not_implemented},
    [0x14] = {"RL H", 2, 8, true, not_implemented},
    [0x15] = {"RL L", 2, 8, true, not_implemented},
    [0x16] = {"RL HL", 2, 16, false, not_implemented},
    [0x17] = {"RL A", 2, 8, true, not_implemented},
    [0x18] = {"RR B", 2, 8, true, not_implemented},
    [0x19] = {"RR C", 2, 8, true, not_implemented},
    [0x1A] = {"RR D", 2, 8, true, not_implemented},
    [0x1B] = {"RR E", 2, 8, true, not_implemented},
    [0x1C] = {"RR H", 2, 8, true, not_implemented},
    [0x1D] = {"RR L", 2, 8, true, not_implemented},
    [0x1E] = {"RR HL", 2, 16, false, not_implemented},
    [0x1F] = {"RR A", 2, 8, true, not_implemented},
    [0x20] = {"SLA B", 2, 8, true, not_implemented},
    [0x21] = {"SLA C", 2, 8, true, not_implemented},
    [0x22] = {"SLA D", 2, 8, true, not_implemented},
    [0x23] = {"SLA E", 2, 8, true, not_implemented},
    [0x24] = {"SLA H", 2, 8, true, not_implemented},
    [0x25] = {"SLA L", 2, 8, true, not_implemented},
    [0x26] = {"SLA HL", 2, 16, false, not_implemented},
    [0x27] = {"SLA A", 2, 8, true, not_implemented},
    [0x28] = {"SRA B", 2, 8, true, not_implemented},
    [0x29] = {"SRA C", 2, 8, true, not_implemented},
    [0x2A] = {"SRA D", 2, 8, true, not_implemented},
    [0x2B] = {"SRA E", 2, 8, true, not_implemented},
    [0x2C] = {"SRA H", 2, 8, true, not_implemented},
    [0x2D] = {"SRA L", 2, 8, true, not_implemented},
    [0x2E] = {"SRA HL", 2, 16, false, not_implemented},
    [0x2F] = {"SRA A", 2, 8, true, not_implemented},
    [0x30] = {"SWAP B", 2, 8, true, not_implemented},
    [0x31] = {"SWAP C", 2, 8, true, not_implemented},
    [0x32] = {"SWAP D", 2, 8, true, not_implemented},
    [0x33] = {"SWAP E", 2, 8, true, not_implemented},
    [0x34] = {"SWAP H", 2, 8, true, not_implemented},
    [0x35] = {"SWAP L", 2, 8, true, not_implemented},
    [0x36] = {"SWAP HL", 2, 16, false, not_implemented},
    [0x37] = {"SWAP A", 2, 8, true, not_implemented},
    [0x38] = {"SRL B", 2, 8, true, not_implemented},
    [0x39] = {"SRL C", 2, 8, true, not_implemented},
    [0x3A] = {"SRL D", 2, 8, true, not_implemented},
    [0x3B] = {"SRL E", 2, 8, true, not_implemented},
    [0x3C] = {"SRL H", 2, 8, true, not_implemented},
    [0x3D] = {"SRL L", 2, 8, true, not_implemented},
    [0x3E] = {"SRL HL", 2, 16, false, not_implemented},
    [0x3F] = {"SRL A", 2, 8, true, not_implemented},
    [0x40] = {"BIT 0", 2, 8, true, not_implemented},
    [0x41] = {"BIT 0", 2, 8, true, not_implemented},
    [0x42] = {"BIT 0", 2, 8, true, not_implemented},
    [0x43] = {"BIT 0", 2, 8, true, not_implemented},
    [0x44] = {"BIT 0", 2, 8, true, not_implemented},
    [0x45] = {"BIT 0", 2, 8, true, not_implemented},
    [0x46] = {"BIT 0", 2, 12, false, not_implemented},
    [0x47] = {"BIT 0", 2, 8, true, not_implemented},
    [0x48] = {"BIT 1", 2, 8, true, not_implemented},
    [0x49] = {"BIT 1", 2, 8, true, not_implemented},
    [0x4A] = {"BIT 1", 2, 8, true, not_implemented},
    [0x4B] = {"BIT 1", 2, 8, true, not_implemented},
    [0x4C] = {"BIT 1", 2, 8, true, not_implemented},
    [0x4D] = {"BIT 1", 2, 8, true, not_implemented},
    [0x4E] = {"BIT 1", 2, 12, false, not_implemented},
    [0x4F] = {"BIT 1", 2, 8, true, not_implemented},
    [0x50] = {"BIT 2", 2, 8, true, not_implemented},
    [0x51] = {"BIT 2", 2, 8, true, not_implemented},
    [0x52] = {"BIT 2", 2, 8, true, not_implemented},
    [0x53] = {"BIT 2", 2, 8, true, not_implemented},
    [0x54] = {"BIT 2", 2, 8, true, not_implemented},
    [0x55] = {"BIT 2", 2, 8, true, not_implemented},
    [0x56] = {"BIT 2", 2, 12, false, not_implemented},
    [0x57] = {"BIT 2", 2, 8, true, not_implemented},
    [0x58] = {"BIT 3", 2, 8, true, not_implemented},
    [0x59] = {"BIT 3", 2, 8, true, not_implemented},
    [0x5A] = {"BIT 3", 2, 8, true, not_implemented},
    [0x5B] = {"BIT 3", 2, 8, true, not_implemented},
    [0x5C] = {"BIT 3", 2, 8, true, not_implemented},
    [0x5D] = {"BIT 3", 2, 8, true, not_implemented},
    [0x5E] = {"BIT 3", 2, 12, false, not_implemented},
    [0x5F] = {"BIT 3", 2, 8, true, not_implemented},
    [0x60] = {"BIT 4", 2, 8, true, not_implemented},
    [0x61] = {"BIT 4", 2, 8, true, not_implemented},
    [0x62] = {"BIT 4", 2, 8, true, not_implemented},
    [0x63] = {"BIT 4", 2, 8, true, not_implemented},
    [0x64] = {"BIT 4", 2, 8, true, not_implemented},
    [0x65] = {"BIT 4", 2, 8, true, not_implemented},
    [0x66] = {"BIT 4", 2, 12, false, not_implemented},
    [0x67] = {"BIT 4", 2, 8, true, not_implemented},
    [0x68] = {"BIT 5", 2, 8, true, not_implemented},
    [0x69] = {"BIT 5", 2, 8, true, not_implemented},
    [0x6A] = {"BIT 5", 2, 8, true, not_implemented},
    [0x6B] = {"BIT 5", 2, 8, true, not_implemented},
    [0x6C] = {"BIT 5", 2, 8, true, not_implemented},
    [0x6D] = {"BIT 5", 2, 8, true, not_implemented},
    [0x6E] = {"BIT 5", 2, 12, false, not_implemented},
    [0x6F] = {"BIT 5", 2, 8, true, not_implemented},
    [0x70] = {"BIT 6", 2, 8, true, not_implemented},
    [0x71] = {"BIT 6", 2, 8, true, not_implemented},
    [0x72] = {"BIT 6", 2, 8, true, not_implemented},
    [0x73] = {"BIT 6", 2, 8, true, not_implemented},
    [0x74] = {"BIT 6", 2, 8, true, not_implemented},
    [0x75] = {"BIT 6", 2, 8, true, not_implemented},
    [0x76] = {"BIT 6", 2, 12, false, not_implemented},
    [0x77] = {"BIT 6", 2, 8, true, not_implemented},
    [0x78] = {"BIT 7", 2, 8, true, not_implemented},
    [0x79] = {"BIT 7", 2, 8, true, not_implemented},
    [0x7A] = {"BIT 7", 2, 8, true, not_implemented},
    [0x7B] = {"BIT 7", 2, 8, true, not_implemented},
    [0x7C] = {"BIT 7", 2, 8, true, not_implemented},
    [0x7D] = {"BIT 7", 2, 8, true, not_implemented},
    [0x7E] = {"BIT 7", 2, 12, false, not_implemented},
    [0x7F] = {"BIT 7", 2, 8, true, not_implemented},
    [0x80] = {"RES 0", 2, 8, true, not_implemented},
    [0x81] = {"RES 0", 2, 8, true, not_implemented},
    [0x82] = {"RES 0", 2, 8, true, not_implemented},
    [0x83] = {"RES 0", 2, 8, true, not_implemented},
    [0x84] = {"RES 0", 2, 8, true, not_implemented},
    [0x85] = {"RES 0", 2, 8, true, not_implemented},
    [0x86] = {"RES 0", 2, 16, false, not_implemented},
    [0x87] = {"RES 0", 2, 8, true, not_implemented},
    [0x88] = {"RES 1", 2, 8, true, not_implemented},
    [0x89] = {"RES 1", 2, 8, true, not_implemented},
    [0x8A] = {"RES 1", 2, 8, true, not_implemented},
    [0x8B] = {"RES 1", 2, 8, true, not_implemented},
    [0x8C] = {"RES 1", 2, 8, true, not_implemented},
    [0x8D] = {"RES 1", 2, 8, true, not_implemented},
    [0x8E] = {"RES 1", 2, 16, false, not_implemented},
    [0x8F] = {"RES 1", 2, 8, true, not_implemented},
    [0x90] = {"RES 2", 2, 8, true, not_implemented},
    [0x91] = {"RES 2", 2, 8, true, not_implemented},
    [0x92] = {"RES 2", 2, 8, true, not_implemented},
    [0x93] = {"RES 2", 2, 8, true, not_implemented},
    [0x94] = {"RES 2", 2, 8, true, not_implemented},
    [0x95] = {"RES 2", 2, 8, true, not_implemented},
    [0x96] = {"RES 2", 2, 16, false, not_implemented},
    [0x97] = {"RES 2", 2, 8, true, not_implemented},
    [0x98] = {"RES 3", 2, 8, true, not_implemented},
    [0x99] = {"RES 3", 2, 8, true, not_implemented},
    [0x9A] = {"RES 3", 2, 8, true, not_implemented},
    [0x9B] = {"RES 3", 2, 8, true, not_implemented},
    [0x9C] = {"RES 3", 2, 8, true, not_implemented},
    [0x9D] = {"RES 3", 2, 8, true, not_implemented},
    [0x9E] = {"RES 3", 2, 16, false, not_implemented},
    [0x9F] = {"RES 3", 2, 8, true, not_implemented},
    [0xA0] = {"RES 4", 2, 8, true, not_implemented},
    [0xA1] = {"RES 4", 2, 8, true, not_implemented},
    [0xA2] = {"RES 4", 2, 8, true, not_implemented},
    [0xA3] = {"RES 4", 2, 8, true, not_implemented},
    [0xA4] = {"RES 4", 2, 8, true, not_implemented},
    [0xA5] = {"RES 4", 2, 8, true, not_implemented},
    [0xA6] = {"RES 4", 2, 16, false, not_implemented},
    [0xA7] = {"RES 4", 2, 8, true, not_implemented},
    [0xA8] = {"RES 5", 2, 8, true, not_implemented},
    [0xA9] = {"RES 5", 2, 8, true, not_implemented},
    [0xAA] = {"RES 5", 2, 8, true, not_implemented},
    [0xAB] = {"RES 5", 2, 8, true, not_implemented},
    [0xAC] = {"RES 5", 2, 8, true, not_implemented},
    [0xAD] = {"RES 5", 2, 8, true, not_implemented},
    [0xAE] = {"RES 5", 2, 16, false, not_implemented},
    [0xAF] = {"RES 5", 2, 8, true, not_implemented},
    [0xB0] = {"RES 6", 2, 8, true, not_implemented},
    [0xB1] = {"RES 6", 2, 8, true, not_implemented},
    [0xB2] = {"RES 6", 2, 8, true, not_implemented},
    [0xB3] = {"RES 6", 2, 8, true, not_implemented},
    [0xB4] = {"RES 6", 2, 8, true, not_implemented},
    [0xB5] = {"RES 6", 2, 8, true, not_implemented},
    [0xB6] = {"RES 6", 2, 16, false, not_implemented},
    [0xB7] = {"RES 6", 2, 8, true, not_implemented},
    [0xB8] = {"RES 7", 2, 8, true, not_implemented},
    [0xB9] = {"RES 7", 2, 8, true, not_implemented},
    [0xBA] = {"RES 7", 2, 8, true, not_implemented},
    [0xBB] = {"RES 7", 2, 8, true, not_implemented},
    [0xBC] = {"RES 7", 2, 8, true, not_implemented},
    [0xBD] = {"RES 7", 2, 8, true, not_implemented},
    [0xBE] = {"RES 7", 2, 16, false, not_implemented},
    [0xBF] = {"RES 7", 2, 8, true, not_implemented},
    [0xC0] = {"SET 0", 2, 8, true, not_implemented},
    [0xC1] = {"SET 0", 2, 8, true, not_implemented},
    [0xC2] = {"SET 0", 2, 8, true, not_implemented},
    [0xC3] = {"SET 0", 2, 8, true, not_implemented},
    [0xC4] = {"SET 0", 2, 8, true, not_implemented},
    [0xC5] = {"SET 0", 2, 8, true, not_implemented},
    [0xC6] = {"SET 0", 2, 16, false, not_implemented},
    [0xC7] = {"SET 0", 2, 8, true, not_implemented},
    [0xC8] = {"SET 1", 2, 8, true, not_implemented},
    [0xC9] = {"SET 1", 2, 8, true, not_implemented},
    [0xCA] = {"SET 1", 2, 8, true, not_implemented},
    [0xCB] = {"SET 1", 2, 8, true, not_implemented},
    [0xCC] = {"SET 1", 2, 8, true, not_implemented},
    [0xCD] = {"SET 1", 2, 8, true, not_implemented},
    [0xCE] = {"SET 1", 2, 16, false, not_implemented},
    [0xCF] = {"SET 1", 2, 8, true, not_implemented},
    [0xD0] = {"SET 2", 2, 8, true, not_implemented},
    [0xD1] = {"SET 2", 2, 8, true, not_implemented},
    [0xD2] = {"SET 2", 2, 8, true, not_implemented},
    [0xD3] = {"SET 2", 2, 8, true, not_implemented},
    [0xD4] = {"SET 2", 2, 8, true, not_implemented},
    [0xD5] = {"SET 2", 2, 8, true, not_implemented},
    [0xD6] = {"SET 2", 2, 16, false, not_implemented},
    [0xD7] = {"SET 2", 2, 8, true, not_implemented},
    [0xD8] = {"SET 3", 2, 8, true, not_implemented},
    [0xD9] = {"SET 3", 2, 8, true, not_implemented},
    [0xDA] = {"SET 3", 2, 8, true, not_implemented},
    [0xDB] = {"SET 3", 2, 8, true, not_implemented},
    [0xDC] = {"SET 3", 2, 8, true, not_implemented},
    [0xDD] = {"SET 3", 2, 8, true, not_implemented},
    [0xDE] = {"SET 3", 2, 16, false, not_implemented},
    [0xDF] = {"SET 3", 2, 8, true, not_implemented},
    [0xE0] = {"SET 4", 2, 8, true, not_implemented},
    [0xE1] = {"SET 4", 2, 8, true, not_implemented},
    [0xE2] = {"SET 4", 2, 8, true, not_implemented},
    [0xE3] = {"SET 4", 2, 8, true, not_implemented},
    [0xE4] = {"SET 4", 2, 8, true, not_implemented},
    [0xE5] = {"SET 4", 2, 8, true, not_implemented},
    [0xE6] = {"SET 4", 2, 16, false, not_implemented},
    [0xE7] = {"SET 4", 2, 8, true, not_implemented},
    [0xE8] = {"SET 5", 2, 8, true, not_implemented},
    [0xE9] = {"SET 5", 2, 8, true, not_implemented},
    [0xEA] = {"SET 5", 2, 8, true, not_implemented},
    [0xEB] = {"SET 5", 2, 8, true, not_implemented},
    [0xEC] = {"SET 5", 2, 8, true, not_implemented},
    [0xED] = {"SET 5", 2, 8, true, not_implemented},
    [0xEE] = {"SET 5", 2, 16, false, not_implemented},
    [0xEF] = {"SET 5", 2, 8, true, not_implemented},
    [0xF0] = {"SET 6", 2, 8, true, not_implemented},
    [0xF1] = {"SET 6", 2, 8, true, not_implemented},
    [0xF2] = {"SET 6", 2, 8, true, not_implemented},
    [0xF3] = {"SET 6", 2, 8, true, not_implemented},
    [0xF4] = {"SET 6", 2, 8, true, not_implemented},
    [0xF5] = {"SET 6", 2, 8, true, not_implemented},
    [0xF6] = {"SET 6", 2, 16, false, not_implemented},
    [0xF7] = {"SET 6", 2, 8, true, not_implemented},
    [0xF8] = {"SET 7", 2, 8, true, not_implemented},
    [0xF9] = {"SET 7", 2, 8, true, not_implemented},
    [0xFA] = {"SET 7", 2, 8, true, not_implemented},
    [0xFB] = {"SET 7", 2, 8, true, not_implemented},
    [0xFC] = {"SET 7", 2, 8, true, not_implemented},
    [0xFD] = {"SET 7", 2, 8, true, not_implemented},
    [0xFE] = {"SET 7", 2, 16, false, not_implemented},
    [0xFF] = {"SET 7", 2, 8, true, not_implemented},
};

void init_cpu(){
    BYTE Cartridge[0x200000];
    BYTE rom[0x10000] = {0};

    register_AF.full = 0x01B0;
    register_BC.full = 0x0013;
    register_DE.full = 0x00D8;
    register_HL.full = 0x014D;

    sp.full = 0xFFFE;

    pc = 0x100;
 
    rom[0xFF05] = 0x00 ;
    rom[0xFF06] = 0x00 ;
    rom[0xFF07] = 0x00 ;
    rom[0xFF10] = 0x80 ;
    rom[0xFF11] = 0xBF ;
    rom[0xFF12] = 0xF3 ;
    rom[0xFF14] = 0xBF ;
    rom[0xFF16] = 0x3F ;
    rom[0xFF17] = 0x00 ;
    rom[0xFF19] = 0xBF ;
    rom[0xFF1A] = 0x7F ;
    rom[0xFF1B] = 0xFF ;
    rom[0xFF1C] = 0x9F ;
    rom[0xFF1E] = 0xBF ;
    rom[0xFF20] = 0xFF ;
    rom[0xFF21] = 0x00 ;
    rom[0xFF22] = 0x00 ;
    rom[0xFF23] = 0xBF ;
    rom[0xFF24] = 0x77 ;
    rom[0xFF25] = 0xF3 ;
    rom[0xFF26] = 0xF1 ;
    rom[0xFF40] = 0x91 ;
    rom[0xFF42] = 0x00 ;
    rom[0xFF43] = 0x00 ;
    rom[0xFF45] = 0x00 ;
    rom[0xFF47] = 0xFC ;
    rom[0xFF48] = 0xFF ;
    rom[0xFF49] = 0xFF ;
    rom[0xFF4A] = 0x00 ;
    rom[0xFF4B] = 0x00 ;
    rom[0xFFFF] = 0x00 ; 
}

void cpu_step(){
    BYTE instruction = rom[pc];
    WORD operand = 0;
    int prefixed = 0;
    if (instruction == 0xCB) prefixed = 1;
    pc += 1;


    if(!prefixed){
        if(unprefixed_instructions[instruction].bytes == 2){
            operand = rom[pc];
        }
        if(unprefixed_instructions[instruction].bytes == 3){
            operand = rom[pc] | rom[pc + 1] << 8;
        }
        LOG_I("[EXECUTING] 0x%x | %s", instruction, unprefixed_instructions[instruction].mnemonic);
        ((void (*)(void))unprefixed_instructions[instruction].execute)();
    }
    
    
}

void WriteToMemory(WORD address, BYTE data){
    
}






